# ==========================================================
# GuardianX Security Notification Model
#
# Per-user security alerts generated by the scanners, the AI
# Assistant and the notification service itself.
#
# PRIVACY GUARANTEES:
#   - Each row belongs to exactly one user (user_id) and is
#     only ever read or written for the logged-in user.
#   - Notification messages are safe summaries only. Raw
#     passwords, full SMS messages, full email bodies, OTPs,
#     PINs, CVVs, tokens and full QR payloads are NEVER stored.
#   - `destination` holds a safe internal route URL built with
#     url_for() so the frontend can navigate without exposing
#     any raw input content.
# ==========================================================

from datetime import datetime

from database.db import db


class Notification(db.Model):

    __tablename__ = "notifications"

    id = db.Column(
        db.Integer,
        primary_key=True
    )

    user_id = db.Column(
        db.Integer,
        db.ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    # email | url | sms | qr | password | ai_assistant |
    # history | system
    notification_type = db.Column(
        db.String(30),
        nullable=False,
        index=True
    )

    title = db.Column(
        db.String(200),
        nullable=False
    )

    message = db.Column(
        db.Text,
        nullable=False
    )

    # INFO | LOW | MEDIUM | HIGH | CRITICAL
    severity = db.Column(
        db.String(10),
        nullable=False,
        default="INFO",
        index=True
    )

    # Links to the matching scan_history entry when available.
    related_scan_id = db.Column(
        db.Integer,
        nullable=True
    )

    # Safe internal route URL (url_for). The frontend falls back
    # to this when a type -> route mapping lookup is needed.
    destination = db.Column(
        db.String(255),
        nullable=True
    )

    is_read = db.Column(
        db.Boolean,
        nullable=False,
        default=False,
        index=True
    )

    # Client-provided idempotency key used to avoid duplicate
    # notifications when the same scan request is retried.
    request_id = db.Column(
        db.String(64),
        nullable=True,
        index=True
    )

    created_at = db.Column(
        db.DateTime,
        default=datetime.utcnow,
        index=True
    )

    __table_args__ = (
        db.Index(
            "ix_notifications_user_created",
            "user_id",
            "created_at"
        ),
    )

    def __repr__(self):

        return "<Notification {} {}>".format(
            self.id,
            self.notification_type
        )
